---
services:
  boca-web:
    build:
      context: .
      dockerfile: docker/web-latex/Dockerfile
    image: caramel-coders/boca-web-latex:local
    depends_on:
      - boca-db
    deploy:
      mode: global
      placement:
        constraints:
          - node.role==manager
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      restart_policy:
        condition: on-failure

  boca-jail:
    image: ghcr.io/joaofazolo/boca-docker/boca-jail:latest
    depends_on:
      - boca-db
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 8
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      restart_policy:
        condition: on-failure

  boca-db:
    deploy:
      mode: global
      placement:
        constraints:
          - node.role==manager
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
        reservations:
          cpus: '0.25'
          memory: 1024M
      restart_policy:
        condition: on-failure
